[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python bot.py"

[start]
cmd = "TF_CPP_MIN_LOG_LEVEL=3 python bot.py"

[phases.install]
cmds = [
    "pip install opencv-python-headless"  # به جای opencv-python معمولی
]
