[phases.setup]
nixPkgs = ["python310"] # فقط پایتون را مشخص می کنیم. Nixpacks به طور خودکار pip را فراهم می کند.

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "pip install opencv-python-headless" # OpenCV رو هم اینجا نصب می کنیم
]

[start]
cmd = "TF_CPP_MIN_LOG_LEVEL=3 python main.py" # فقط یک استارت دستور داریم. اگر نیاز بود می توانستیم دستورات را با && به هم وصل کنیم.
